name: ammp-connect-wg
version: '0+git' 
summary: AMMP Connect via WireGuard
description: |
  AMMP connect via WireGuard
grade: devel
confinement: devmode

apps:
  wg:
    command: wg
    plugs: [network, home]
  wg-quick:
    command: wg-quick
    plugs: [network, home]
  wireguard-go:
    command: wireguard-go
    plugs: [network, home]


parts:
  wireguard:
    plugin: make
    source-type: git
    source: https://git.zx2c4.com/WireGuard
    source-tag: 0.0.20181007
    source-subdir: src/tools/
    build-packages:
      - libmnl-dev
      - build-essential
  go:
    source-tag: go1.10
  wireguard-go:
    after: [go]
    plugin: make
    source-type: git
    source: https://git.zx2c4.com/wireguard-go
    source-tag: 0.0.20181001
    # plugin: go
    # source: .
    # go-importpath: git.zx2c4.com/wireguard-go