name: wireguard-ammp
version: '0.0.20181018'
summary: WireGuard VPN (userspace)
description: |
  WireGuard® is an extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography. It aims to be faster, simpler, leaner, and more useful than IPSec, while avoiding the massive headache. It intends to be considerably more performant than OpenVPN.
  This snap packages wireguard-go userspace executable (https://git.zx2c4.com/wireguard-go/about/) and the wg and wg-quick binaries from the main repo (https://git.zx2c4.com/WireGuard/about/)
grade: stable
confinement: strict

apps:
  wg:
    command: wg
    plugs: [network, network-control, network-bind]
  wg-quick:
    command: wg-quick
    plugs: [network, network-control, network-bind]
    environment:
      WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD: 1
      WG_SOCKET_DIR: $SNAP_DATA/socket
  wireguard-go:
    command: wireguard-go
    plugs: [network, network-control]
    environment:
      WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD: 1
      WG_SOCKET_DIR: $SNAP_DATA/socket

parts:
  wireguard:
    plugin: make
    source-type: git
    source: https://github.com/svet-b/WireGuard.git
    source-branch: 0.0.20181018
    source-subdir: src/tools/
    build-packages:
      - libmnl-dev
      - build-essential
    stage-packages:
      - libc6
    make-parameters: [WITH_WGQUICK=yes]
  go:
    source-tag: go1.11
  wireguard-go:
    after: [go]
    plugin: make
    source-type: git
    source: https://github.com/svet-b/wireguard-go.git
    source-branch: 0.0.20181018

passthrough:
  layout:
    /etc/wireguard:
      bind: $SNAP_COMMON/etc/wireguard
